// Seed data for the Earth & Essence opportunity finder.
// Seller IDs are Amazon UK "merchant" (storefront) IDs whose catalogues
// overlap with the wellness / herbal-drops / supplement niche.

export const SELLERS_BY_CATEGORY = {
  earth_essence: [
  { seller_id: 'AHTJ4NZJTT4RD', label: 'Storefront 1' },
  { seller_id: 'A1TLSU4JIFJ2PE', label: 'Storefront 2' },
  { seller_id: 'A3HQDOVPCW4FLZ', label: 'Storefront 3' },
  { seller_id: 'A11TBTV5AJWNLW', label: 'Storefront 4' },
  { seller_id: 'A2RIXOKE9P7EQR', label: 'Storefront 5' },
  { seller_id: 'A2EUS4P6UET99R', label: 'Storefront 6' },
  { seller_id: 'A1QD1Z1XXPTQ5M', label: 'Storefront 7' },
  { seller_id: 'A2608ETDP1KP7Q', label: 'Storefront 8' },
  { seller_id: 'AE762XRTAJIJ3', label: 'Storefront 9' },
  { seller_id: 'A3N42UXRN3C50P', label: 'Storefront 10' },
  { seller_id: 'A31KBH0XIR7WKQ', label: 'Storefront 11' },
  { seller_id: 'A61W1BU3RO3XT', label: 'Storefront 12' },
  { seller_id: 'A3TMIFG02Y3Y5Q', label: 'Storefront 13' },
  { seller_id: 'AEV63UW7OJPZ0', label: 'Storefront 14' },
  { seller_id: 'AQEX692DU3E1V', label: 'Storefront 15' },
  ],
  // Pure Pleasure (sexual wellness) has no tracked storefronts yet - this
  // category's opportunities are scored purely from seed-keyword search
  // demand/competition, with no storefront-discovered candidates.
  pure_pleasure: [],
};

// Starter niche keywords aligned with Earth & Essence's positioning
// (liquid herbal drops / extracts, detox & lymphatic wellness).
// The scanner extends this list dynamically with candidates extracted
// from storefront product titles.
export const SEED_KEYWORDS_BY_CATEGORY = {
  earth_essence: [
  'ashwagandha drops',
  'elderberry extract drops',
  'magnesium glycinate liquid drops',
  'black seed oil drops',
  'valerian root drops',
  'dandelion root liquid extract',
  'milk thistle liquid extract',
  'mullein leaf extract drops',
  'beetroot extract drops',
  'rhodiola rosea drops',
  'nettle leaf extract drops',
  'liver detox drops',
  'berberine liquid drops',
  'chlorophyll liquid drops',
  "cat's claw extract drops",
  'turmeric liquid extract drops',
  'ginger root extract drops',
  'iodine drops',
  'vitamin d3 k2 drops',
  'wormwood extract drops',
  'echinacea liquid extract',
  'oregano oil drops',
  'astragalus root extract drops',
  'burdock root liquid extract',
  'passionflower extract drops',
  'sea moss liquid drops',
  'maca root liquid extract',
  'water retention tablets',
  'water retention drops',
  'lymphatic support water retention capsules',
  'water retention capsules',
  'lymphatic support capsules',
  'ceylon cinnamon mct softgels',
  'astaxanthin capsules',
  'capsaicin hawthorn circulation capsules',

  // --- Adaptogens & energy ---
  'ashwagandha capsules',
  'ashwagandha tablets',
  'ashwagandha gummies',
  'rhodiola rosea capsules',
  'rhodiola rosea tablets',
  'rhodiola gummies',
  'panax ginseng capsules',
  'panax ginseng drops',
  'siberian ginseng extract drops',
  'siberian ginseng capsules',
  'holy basil tulsi drops',
  'holy basil tulsi capsules',
  'schisandra berry extract drops',
  'schisandra berry capsules',
  'maca root capsules',
  'maca root tablets',
  'maca root gummies',
  'cordyceps mushroom capsules',
  'cordyceps extract drops',
  'cordyceps powder',
  'reishi mushroom extract drops',
  'reishi mushroom capsules',
  'reishi mushroom powder',
  "lion's mane extract drops",
  "lion's mane capsules",
  "lion's mane gummies",
  "lion's mane powder",
  'chaga mushroom extract drops',
  'chaga mushroom powder',
  'eleuthero root extract drops',
  'bacopa monnieri extract drops',
  'bacopa monnieri capsules',
  'gotu kola extract drops',
  'gotu kola capsules',
  'ginkgo biloba extract drops',
  'ginkgo biloba capsules',
  'ginkgo biloba tablets',

  // --- Calm / sleep / mood ---
  'l-theanine capsules',
  'l-theanine gummies',
  'gaba supplement capsules',
  '5-htp capsules',
  '5-htp drops',
  'valerian root capsules',
  'valerian root tablets',
  'passionflower extract capsules',
  'passionflower gummies',
  'lemon balm extract drops',
  'lemon balm capsules',
  'skullcap extract drops',
  'chamomile extract drops',
  'melatonin gummies',
  'melatonin drops',
  'melatonin tablets',
  'magnesium glycinate capsules',
  'magnesium glycinate tablets',
  'magnesium glycinate gummies',
  'magnesium taurate capsules',
  'magnesium l-threonate capsules',
  'magnesium citrate liquid drops',
  'magnesium oil spray',
  'magnesium bisglycinate capsules',

  // --- Digestive / gut health ---
  'milk thistle capsules',
  'milk thistle tablets',
  'milk thistle gummies',
  'dandelion root capsules',
  'dandelion root tablets',
  'dandelion leaf extract capsules',
  'artichoke extract capsules',
  'artichoke extract drops',
  'ginger root capsules',
  'ginger root tablets',
  'ginger root gummies',
  'turmeric ginger capsules',
  'peppermint oil capsules',
  'fennel seed extract drops',
  'fennel seed capsules',
  'slippery elm capsules',
  'marshmallow root extract drops',
  'marshmallow root capsules',
  'licorice root extract drops',
  'licorice root capsules',
  'aloe vera liquid extract',
  'aloe vera capsules',
  'digestive enzymes capsules',
  'probiotic capsules',
  'probiotic gummies',
  'psyllium husk powder',
  'l-glutamine powder',
  'l-glutamine capsules',
  'betaine hcl capsules',
  'betaine hcl pepsin capsules',
  'apple cider vinegar gummies',
  'apple cider vinegar capsules',
  'apple cider vinegar liquid drops',
  'apple cider vinegar tablets',
  'digestive bitters tincture drops',

  // --- Immune support ---
  'elderberry gummies',
  'elderberry capsules',
  'elderberry tablets',
  'elderberry zinc vitamin c gummies',
  'echinacea capsules',
  'echinacea tablets',
  'echinacea gummies',
  'oregano oil capsules',
  'oregano oil softgels',
  'astragalus root capsules',
  'astragalus root tablets',
  'andrographis extract drops',
  'andrographis capsules',
  'propolis extract drops',
  'propolis tincture',
  'propolis capsules',
  'propolis lozenges',
  'colostrum powder',
  'colostrum capsules',
  'colostrum gummies',
  'beta glucan capsules',
  'zinc liquid drops',
  'zinc capsules',
  'zinc tablets',
  'zinc gummies',
  'vitamin c liquid drops',
  'vitamin c gummies',
  'vitamin c tablets',
  'vitamin c rosehip tablets',
  'vitamin d3 liquid drops',
  'vitamin d3 capsules',
  'vitamin d3 gummies',
  'vitamin d3 liquid spray',
  'vitamin d3 k2 capsules',
  'quercetin capsules',
  'quercetin bromelain capsules',
  'immune support gummies for adults',

  // --- Detox / lymphatic / circulation ---
  'burdock root capsules',
  'burdock root tablets',
  'red clover extract drops',
  'red clover capsules',
  'red clover blossom capsules',
  'chlorophyll capsules',
  'chlorophyll tablets',
  'activated charcoal capsules',
  'activated charcoal tablets',
  'activated charcoal powder',
  'bentonite clay powder',
  'diatomaceous earth powder',
  "cat's claw capsules",
  "cat's claw tablets",
  "pau d'arco extract drops",
  "pau d'arco capsules",
  'nettle leaf capsules',
  'nettle leaf tablets',
  'beetroot extract capsules',
  'beetroot extract tablets',
  'beetroot powder',
  'beetroot nitrate capsules',
  'hawthorn berry extract drops',
  'hawthorn berry capsules',
  'hawthorn berry tablets',
  "butcher's broom capsules",
  "butcher's broom extract drops",
  'butchers broom horse chestnut capsules',
  'horse chestnut extract capsules',
  'horse chestnut tablets',
  'grape seed extract capsules',
  'grape seed extract drops',
  'pine bark extract capsules',
  'ginkgo biloba liquid drops',
  'circulation support capsules',
  'varicose vein support capsules',
  'spirulina tablets',
  'spirulina powder',
  'chlorella tablets',
  'chlorella spirulina tablets',
  'wheatgrass powder',
  'wheatgrass tablets',
  'barley grass powder',
  'moringa leaf powder',
  'moringa powder capsules',
  'milk thistle dandelion liver capsules',

  // --- Joint / bone / anti-inflammatory ---
  'turmeric curcumin capsules',
  'turmeric curcumin tablets',
  'turmeric curcumin gummies',
  'curcumin phytosome capsules',
  'boswellia extract capsules',
  'boswellia serrata tablets',
  'boswellia turmeric capsules',
  'glucosamine chondroitin tablets',
  'glucosamine chondroitin capsules',
  'msm capsules',
  'msm powder',
  'msm liquid drops',
  'msm glucosamine capsules',
  'collagen powder',
  'collagen capsules',
  'collagen gummies',
  'collagen peptides powder',
  'type ii collagen capsules',
  'bromelain capsules',
  "devil's claw capsules",
  "devil's claw extract drops",
  'willow bark extract drops',
  'willow bark capsules',
  'green lipped mussel capsules',
  'ginger turmeric tablets',
  'hyaluronic acid capsules',
  'hyaluronic acid liquid drops',
  'hyaluronic acid gummies',

  // --- Women's health ---
  'evening primrose oil capsules',
  'evening primrose oil softgels',
  'evening primrose oil tablets',
  'evening primrose oil for menopause capsules',
  'agnus castus extract drops',
  'agnus castus tablets',
  'chasteberry vitex capsules',
  'red raspberry leaf capsules',
  'red raspberry leaf extract drops',
  'red raspberry leaf tea extract drops',
  'dong quai extract drops',
  'dong quai capsules',
  'dong quai root powder',
  'black cohosh extract drops',
  'black cohosh capsules',
  'cranberry extract capsules',
  'cranberry extract tablets',
  'cranberry d-mannose capsules',
  'maca root capsules for women',
  'multivitamin capsules for women',
  'prenatal vitamin gummies',

  // --- Men's health ---
  'saw palmetto extract drops',
  'saw palmetto capsules',
  'saw palmetto prostate capsules',
  'tribulus terrestris capsules',
  'nettle root extract capsules',
  'pumpkin seed oil softgels',
  'zinc magnesium prostate capsules',
  'multivitamin capsules for men',

  // --- Weight management / metabolism ---
  'green tea extract capsules',
  'green tea extract drops',
  'raspberry ketones capsules',
  'garcinia cambogia capsules',
  'glucomannan capsules',
  'glucomannan tablets',
  'chromium picolinate tablets',
  'l-carnitine liquid drops',
  'l-carnitine capsules',
  'cla supplement capsules',
  'green coffee bean extract capsules',
  'african mango extract capsules',
  'white kidney bean extract capsules',
  'konjac root capsules',
  'metabolism support capsules',
  'thermogenic fat burner capsules',

  // --- Vitamins & minerals ---
  'vitamin b12 liquid drops',
  'vitamin b12 gummies',
  'vitamin b12 tablets',
  'vitamin b12 sublingual drops',
  'vitamin b complex liquid drops',
  'b-complex capsules',
  'iron liquid drops',
  'iron gummies',
  'iron tablets',
  'folate capsules',
  'folic acid liquid drops',
  'calcium liquid drops',
  'calcium magnesium zinc tablets',
  'calcium d3 tablets',
  'potassium liquid drops',
  'potassium capsules',
  'selenium liquid drops',
  'selenium capsules',
  'vitamin k2 liquid drops',
  'vitamin k2 capsules',
  'vitamin a liquid drops',
  'vitamin a capsules',
  'vitamin e liquid drops',
  'vitamin e capsules',
  'trace minerals liquid drops',
  'multivitamin liquid drops',
  'multivitamin gummies for adults',
  'chromium capsules',
  'copper capsules',
  'manganese capsules',
  'molybdenum capsules',

  // --- Skin / hair / beauty ---
  'biotin liquid drops',
  'biotin gummies',
  'biotin capsules',
  'silica capsules',
  'horsetail extract drops',
  'horsetail capsules',
  'keratin hair gummies',
  'bee pollen capsules',
  'royal jelly capsules',
  'manuka honey lozenges',

  // --- Energy / cognitive ---
  'b-complex liquid drops',
  'coq10 capsules',
  'coq10 softgels',
  'coq10 ubiquinol capsules',
  'guarana extract capsules',
  'nadh capsules',
  'pqq capsules',
  'ginkgo biloba ginseng capsules',
  'phosphatidylserine capsules',
  'lutein zeaxanthin capsules',
  'bilberry extract capsules',
  'dha algae oil capsules',

  // --- Heart / cardiovascular ---
  'omega 3 fish oil softgels',
  'omega 3 liquid drops',
  'garlic extract capsules',
  'garlic extract tablets',
  'niacin capsules',
  'krill oil softgels',
  'cod liver oil softgels',

  // --- Liver support ---
  'nac n-acetyl cysteine capsules',
  'glutathione capsules',
  'liver detox capsules',
  'liver detox tablets',
  'schisandra liver support capsules',

  // --- Other wellness / sports ---
  'matcha green tea powder',
  'ginseng root powder',
  'turmeric powder capsules',
  'ceylon cinnamon capsules',
  'ceylon cinnamon tablets',
  'cinnamon extract capsules',
  'fenugreek capsules',
  'fenugreek extract drops',
  'black seed oil capsules',
  'black seed oil softgels',
  'hemp seed oil softgels',
  'flaxseed oil softgels',
  'shark cartilage capsules',
  'electrolyte powder sachets',
  'creatine monohydrate powder',
  'bcaa powder',
  'l-arginine capsules',
  'beta alanine powder',
  'tart cherry extract capsules',
  'tart cherry juice powder',
  'spirea extract drops',
  'wellmune beta glucan capsules',
  'activated charcoal teeth whitening powder',

  // --- Storefront-stalking finds (live-scored, validated by repeated
  // cross-seller "X+ bought in past month" badges on low-review listings) ---
  'aged garlic extract capsules',
  'aged garlic extract softgels',
  'multi collagen capsules',
  'cortisol support capsules',
  'beetroot extract gummies',
  'liposomal vitamin c softgels',
  'nac nad capsules',
  'ahcc capsules',
  'wormwood black walnut clove capsules',
  'wormwood black walnut clove drops',
  'nad+ capsules',
  'plant sterols capsules',
  'turkesterone capsules',

  // --- Round 2 storefront-stalking finds (live-scored 2026-06-15) ---
  'black garlic extract capsules',
  'tongkat ali capsules',
  'mucuna pruriens capsules',

  // --- Round 3 storefront-stalking finds (live-scored 2026-06-15) ---
  'glycine capsules',
  'zinc carnosine capsules',

  // --- Round 7 storefront-stalking finds (live-scored 2026-06-15) ---
  'berberine gummies',
  'rhodiola rosea capsules',
  'saffron extract capsules',

  // --- Round 8 storefront-stalking finds (live-scored 2026-06-15) ---
  'ceylon cinnamon capsules',
  'schisandra berry capsules',
  'white mulberry leaf extract capsules',
  'cyperus rotundus oil',
  ],

  // Starter niche keywords for Pure Pleasure (Amazon UK "Health & Personal
  // Care > Sexual Wellbeing"). Pure Pleasure already sells a wand
  // vibrator/handheld massager and a thrusting rabbit vibrator, so those
  // exact niches are excluded via isOwnProductNiche() rather than re-seeded
  // here. The scanner has no storefronts to extract candidates from for this
  // category, so this list is the sole source of keywords.
  pure_pleasure: [
    // --- Bullet & mini vibrators ---
    'bullet vibrator',
    'mini bullet vibrator',
    'finger vibrator',
    'lipstick vibrator',
    'discreet mini vibrator',
    'clitoral bullet vibrator',
    'rechargeable bullet vibrator',
    'vibrating egg bullet',
    'travel size vibrator',

    // --- Clitoral stimulators ---
    'clitoral suction vibrator',
    'air pulse clitoral stimulator',
    'rose toy vibrator',
    'tongue vibrator clitoral',
    'clit sucking vibrator',
    'nipple and clit sucker',
    'clitoral stimulator silicone',

    // --- G-spot & insertable vibrators ---
    'g spot vibrator',
    'realistic dildo vibrator',
    'vibrating dildo',
    'curved g spot massager',
    'silicone g spot wand',
    'dual stimulation vibrator',
    '10 speed vibrator women',
    'waterproof vibrator for women',
    'quiet vibrator discreet',

    // --- Wearable / remote control ---
    'wearable clitoral vibrator',
    'panty vibrator remote control',
    'app controlled vibrator',
    'remote control love egg',
    'kegel egg vibrator',
    'vibrating egg panties',
    'wearable vibrator for couples',
    'love egg remote control',

    // --- Couples toys / cock rings ---
    'couples vibrator',
    'vibrating cock ring',
    'remote control cock ring',
    'penis ring vibrating',
    'couples ring vibrator',
    'silicone cock ring set',

    // --- Anal toys ---
    'silicone butt plug',
    'anal plug set',
    'anal training kit',
    'vibrating butt plug',
    'anal beads silicone',
    'vibrating anal beads',
    'glass butt plug',
    'remote control butt plug',
    'anal trainer set 3 piece',
    'anal douche silicone',

    // --- Prostate massagers ---
    'prostate massager',
    'vibrating prostate massager',
    'prostate massager remote control',

    // --- Male masturbators / strokers ---
    'male masturbator cup',
    'pocket pussy stroker',
    'penis pump',
    'male stroker sleeve',
    'vibrating male masturbator',
    'automatic male masturbator',
    'penis sleeve extender',
    'ball stretcher silicone',

    // --- Kegel / pelvic floor ---
    'kegel exercise balls',
    'kegel balls set',
    'kegel weights for women',
    'pelvic floor trainer',
    'ben wa balls',

    // --- Massage candles ---
    'massage candle',

    // --- Bondage / BDSM accessories ---
    'bondage restraint kit',
    'silk blindfold set',
    'nipple clamps',
    'feather tickler set',
    'bondage rope kit',
    'fluffy handcuffs set',
    'under bed restraint system',
    'paddle spanking set',
    'silicone gag ball',
    'bondage kit beginners',

    // --- Realistic dildos ---
    'realistic silicone dildo',
    'suction cup dildo',
    'glass dildo',
    'double ended dildo',
    'beginner silicone dildo',

    // --- Nipple toys ---
    'nipple suckers set',
    'nipple vibrator',
    'nipple clamps with bells',

    // --- Toy care & storage ---
    'sex toy cleaner spray',
    'sex toy storage bag',
    'antibacterial toy cleaner',

    // --- Adult games / gifts ---
    'couples game adult',
    'sex dice game',
    'pheromone perfume for women',

    // --- Rotating & motion vibrators (non-rabbit) ---
    'rotating beads vibrator',
    'telescopic vibrator women',
    'inflatable vibrating dildo',
    'pulsing suction cup vibrator',
    'swinging tongue licking vibrator',
    'heating vibrator massager women',
    'multi speed insertable vibrator',
    'realistic vibrating dong',
    'pearl rotating vibrator',
    'expanding vibrator for women',
    'silicone motion massager toy',
    'come hither motion vibrator',

    // --- App-controlled / long distance toys ---
    'bluetooth vibrator app controlled',
    'long distance couples vibrator app',
    'wifi controlled vibrator',
    'interactive vibrator video sync',
    'app controlled cock ring',
    'app controlled butt plug',
    'smart vibrator bluetooth',
    'voice controlled vibrator',
    'magnetic charging app vibrator',
    'app controlled wearable vibrator women',

    // --- Penis sleeves, extenders & enhancement ---
    'penis extender sleeve realistic',
    'girth enhancer sleeve',
    'reusable textured condom sleeve',
    'penis enlargement pump kit',
    'cock sleeve ribbed silicone',
    'penis enhancement ring set',
    'stretchy penis sleeve',
    'vibrating penis extender sleeve',
    'delay spray for men',
    'desensitising spray for men',
    'penis exercise device',
    'cock and ball harness',

    // --- Vibrating cock rings & couples rings ---
    'rechargeable vibrating cock ring',
    'wearable vibrating penis ring',
    'double vibrating cock ring',
    'silicone penis ring set 3 piece',
    'vibrating ring for couples app',
    'stretchy vibrating ring',
    'adjustable cock ring with bullet',
    'waterproof vibrating ring',
    'penis ring with clitoral stimulator',
    'remote control vibrating ring couples',

    // --- Anal toys expansion ---
    'anal vibrator remote control',
    'expanding inflatable butt plug',
    'jewelled butt plug set',
    'silicone anal plug trainer set',
    'vibrating anal beads remote control',
    'prostate vibrator app controlled',
    'anal plug with tail',
    'metal butt plug set',
    'vibrating anal plug rechargeable',
    'anal plug harness',
    'graduated anal training set',
    'silicone anal plug for beginners',
    'anal vibrator with remote for men',
    'butt plug with handle',
    'rechargeable anal massager',

    // --- Prostate massagers expansion ---
    'prostate massager app controlled',
    'prostate massager for beginners',
    'p spot massager silicone',
    'rechargeable prostate stimulator',
    'prostate massager with cock ring',
    'heating prostate massager',
    'rotating prostate massager',
    'waterproof prostate massager',

    // --- Vibrating panties & wearables ---
    'vibrating panties remote control women',
    'wearable panty vibrator app controlled',
    'invisible wearable vibrator',
    'thong vibrator remote control',
    'clitoral vibrator panty set',
    'wireless wearable vibrator women',
    'magnetic wearable vibrator',
    'vibrating brief for women',
    'remote control wearable egg panty',
    'silent wearable vibrator',

    // --- Strap-on & harness ---
    'strap on harness dildo set',
    'pegging strap on kit',
    'adjustable strap on harness',
    'strapless strap on dildo',
    'beginner strap on set',
    'leather strap on harness',
    'hollow strap on for men',
    'double ended strap on dildo',
    'universal harness with dildo',
    'vibrating strap on dildo',

    // --- Nipple & breast toys ---
    'nipple suction pump set',
    'vibrating nipple clamps',
    'nipple tassels pasties',
    'vibrating breast massager',
    'nipple play kit',
    'silicone nipple enhancer',
    'nipple clamps adjustable chain',
    'vibrating nipple sucker set',
    'nipple licking vibrator',
    'breast enhancement pump',

    // --- BDSM expansion ---
    'leather collar with leash',
    'leather riding crop',
    'wax play candle set',
    'sensory deprivation hood',
    'vibrating ball gag',
    'spreader bar restraint',
    'wrist and ankle cuffs set',
    'bondage tape non sticky',
    'over door restraint kit',
    'leather flogger whip',
    'pet play collar set',
    'bondage harness lingerie',
    'restraint kit for bed',
    'feather and flogger sensory set',
    'blindfold and cuffs set',
    'rope bondage kit for beginners',
    'adjustable leather wrist cuffs',
    'pleasure and pain spinner wheel',

    // --- Glass, crystal & metal toys ---
    'pyrex glass dildo curved',
    'crystal glass massage stick',
    'stainless steel anal plug',
    'glass anal plug gift set',
    'glass butt plug with jewel',
    'temperature play glass dildo',
    'rose quartz yoni egg',
    'metal kegel balls set',
    'double ended glass dildo',
    'stainless steel realistic dildo',

    // --- Couples games & roleplay ---
    'couples truth or dare game',
    'scratch off bucket list for couples',
    'sexy dice game for couples',
    'roleplay costume set for adults',
    'spin the bottle adult game',
    'intimacy board game for couples',
    'fantasy roleplay kit for adults',
    'mystery box for couples adult',
    'date night game box for couples',
    'conversation cards for couples intimacy',

    // --- Toy cleaning ---
    'toy cleaning spray unscented',
    'antibacterial wipes for adult toys',

    // --- Libido gummies (edible supplement, not lube/gel) ---
    'maca root arousal gummies for women',
    'horny goat weed gummies for women',

    // --- Storage & travel ---
    'discreet vibrator travel case',
    'locking adult toy storage box',
    'padded toy storage bag with compartments',
    'travel pouch for sex toys',
    'velvet storage bag for vibrator',
    'waterproof toy carrying case',
    'discreet toy bag with lock',
    'silicone toy organiser tray',

    // --- Male masturbator expansion ---
    'realistic vagina masturbator cup',
    'textured masturbation sleeve for men',
    'oral simulator male toy',
    'rechargeable male stroker cup',
    'self lubricating male masturbator',
    'pocket stroker travel size',
    'realistic textured stroker sleeve',
    'vibrating masturbation cup for men',
    'double ended male masturbator',
    'soft skin texture stroker for men',
    'pump action male masturbator',
    'compact discreet male stroker',

    // --- Sensory play (candles, feathers, ice) ---
    'low temperature massage candle',
    'feather tickler and blindfold set',
    'sensory play kit for couples',
    'fur lined cuffs and blindfold set',
    'flogger and feather sensory set',
    'temperature play massage candle gift set',
    'erotic scented massage candle set',
    'sensation play kit for beginners',

    // --- Double-ended & dual toys ---
    'double penetration strap on dildo',
    'flexible double ended dong',
    'dual ended vibrator for couples',
    'double headed realistic dildo',
    'flexible double dong silicone',
    'double sided curved dildo',
    'dual stimulation strap on dildo',
    'double ended glass massage dildo',

    // --- Egg vibrators expansion ---
    'wireless love egg with remote',
    'rechargeable vibrating egg set',
    'silent love egg vibrator',
    'love egg with remote for women',
    'app controlled love egg',
    'mini egg vibrator for travel',
    'dual love egg set',
    'vibrating egg with cock ring',

    // --- Pumps (clitoral, nipple, penis) ---
    'vibrating clitoral suction pump',
    'nipple enhancer pump set',
    'electric penis pump',
    'vacuum pump for men',
    'clit pump with vibration',
    'nipple suction cups set',
    'arousal breast pump',
    'vibrating clitoral pump kit',

    // --- Restraints expansion ---
    'over the door restraint straps',
    'ankle and wrist cuffs bondage set',
    'under mattress bed restraint straps',
    'adjustable bondage straps kit',
    'silk rope restraint set',
    'pillow with built in restraint straps',
    'door swing restraint kit',
    'soft lined bondage cuffs',
    'collar and wrist cuff set',
    'full body restraint harness',

    // --- Realistic dildo expansion ---
    'ribbed realistic silicone dildo',
    'vein textured suction cup dildo',
    'extra large realistic silicone dildo',
    'small beginner silicone dildo',
    'curved g spot silicone dildo',
    'dual density realistic dildo',
    'silicone dildo with balls',
    'colourful silicone dildo for beginners',
    'squirting realistic dildo',
    'thick girthy silicone dildo',

    // --- Couples gift sets ---
    'honeymoon gift set for couples',
    'wedding night gift box for adults',
    'valentines day couples gift set',
    'anniversary gift set for couples adult',
    'romantic night in gift box',
    'couples starter kit toys and lube',
    'date night box for adult couples',
    'newlywed gift set for adults',

    // --- Finger & hand toys ---
    'finger sleeve vibrator',
    'finger vibrator for clitoral stimulation',
    'rechargeable finger massager',
    'thumb vibrator silicone',
    'finger ring vibrator',
    'wearable waterproof finger vibrator',
    'finger massager for couples',
    'mini travel finger massager',

    // --- General female vibrators ---
    'rechargeable vibrator for women',
    'silicone waterproof vibrator for women',
    'compact vibrator for beginners',
    'multi function vibrator for women',
    'whisper quiet rechargeable vibrator',
    'discreet lipstick travel vibrator',
    'vibrator with multiple attachments',
    'usb rechargeable vibrator for women',
    'beginner vibrator set for women',
    'dual motor vibrator for women',

    // --- Anal douches & cleansing ---
    'silicone anal douche bulb',
    'enema bulb kit',
    'shower enema attachment',
    'anal cleansing kit',
    'travel anal douche',
    'large silicone enema bulb',
    'rectal cleansing syringe',
    'silicone anal hygiene kit',

    // --- Cock & ball toys expansion ---
    'cock and ball torture kit',
    'weighted silicone ball stretcher set',
    'penis head stimulator sleeve',
    'glans massager for men',
    'cock ring with ball strap',
    'adjustable weighted ball stretcher',
    'penis glans stimulator sleeve',
    'testicle massager for men',
    'ball gag with cock ring set',
    'silicone cock cage',

    // --- Vibrator attachments & accessories ---
    'vibrator attachment heads set',
    'silicone sleeve for vibrator',
    'replacement vibrator heads',
    'usb vibrator charging cable',
    'silicone vibrator head covers',
    'attachment set for massage device',
    'vibrator extension attachment',
    'silicone covers for bullet vibrator',

    // --- Anal vibrators general ---
    'small anal vibrator for beginners',
    'curved anal vibrator for men',
    'rechargeable silicone anal vibrator',
    'anal vibrator with remote for women',
    'pulsing anal plug vibrator',
    'discreet mini anal vibrator',
    'flexible anal vibrator',
    'anal vibrator with suction base',

    // --- Sex furniture & positioning aids ---
    'sex position pillow wedge',
    'inflatable sex pillow cushion',
    'bondage positioning pillow set',
    'door sex swing',
    'positioning wedge ramp set',
    'inflatable wedge cushion for couples',
    'memory foam sex positioning pillow',
    'door sex sling',

    // --- Intimate wellness for women ---
    'app connected kegel exerciser',
    'electric pelvic floor stimulator',
    'vaginal dilator set',
    'reusable menstrual cup set',

    // --- Penetrative toy sets ---
    'beginner anal kit 4 piece',
    'silicone dildo and vibrator set',
    'starter sex toy kit for women',
    'his and hers couples toy set',
    'lesbian couples toy set',
    'gay men anal toy set',
    'first time couples toy kit',
    'mixed toy gift set for women',

    // --- Specialty vibration tech ---
    'pulse wave clitoral toy',
    'air pressure clitoral toy',
    'sonic vibration massager for women',
    'whisper quiet rechargeable bullet',
    'magnetic charging bullet vibrator',
    'rechargeable mini discreet massager',
    'silent vibrator for shared spaces',
    'travel friendly silent vibrator',

    // --- Lingerie & intimate apparel ---
    'crotchless lace panties',
    'open cup bra set',
    'sheer babydoll lingerie set',
    'fishnet bodystocking',
    'lace teddy lingerie set',
    'harness lingerie bra',
    'garter belt and stockings set',
    'plus size lace lingerie set',
    'roleplay lingerie costume set',
    'bridal lingerie set white',
    'sexy chemise nightwear',
    'strappy adjustable lingerie set',

    // --- Sensual massage tools ---
    'sensual massage roller tool',
    'erotic feather duster',
    'silicone massage mat',
    'couples massage gift set with oil and candle',
    'body massage roller for couples',
    'heated massage stones set',
    'erotic massage kit for couples',

    // --- Mystery boxes & party gifts ---
    'mystery sex toy box',
    'adult subscription box surprise',
    'monthly pleasure box for women',
    'adult party game box',
    'bachelorette party gift set adult',
    'hen party adult game set',
    'adult birthday gift set for women',
    'naughty gift box for him',

    // --- Anal training & beginner sets ---
    'silicone anal training set 3 sizes',
    'soft silicone beginner anal plug',
    'tapered anal plug set',
    'weighted anal plug set',
    'anal plug set with flared base',
    'soft silicone butt plug set for beginners',
    'anal trainer kit with lubricant',
    'progressive anal dilator set',

    // --- Travel & discreet packaging ---
    'discreet packaging vibrator',
    'plain packaging adult toy',
    'travel size couples toy kit',
    'compact rechargeable travel vibrator',
    'discreet adult toy gift wrap',
    'mini keyring vibrator discreet',
    'pocket size clitoral vibrator',
    'usb rechargeable travel toy set',

    // --- Condoms & couples enhancement ---
    'flavoured condoms variety pack',
    'ultra thin condoms pack',
    'textured ribbed dotted condoms',
    'extra large condoms pack',
    'novelty condoms gift pack',
    'latex free condoms pack',
    'glow in the dark condoms',
    'long lasting delay condoms',
    'natural feel condoms pack',
    'silk rope and blindfold gift set',
    'masquerade mask set for couples',
    'cosplay accessory kit for adults',
    'fantasy roleplay accessory set',
    'erotic dice and card game set',
    'temperature play wax candle kit',
  ],
};

export const MARKETPLACE_ID = process.env.AMAZON_MARKETPLACE_ID || 'A1F83G8C2ARO7P';
export const KEEPA_DOMAIN_ID = Number(process.env.KEEPA_DOMAIN_ID || 2); // 2 = amazon.co.uk
